services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Jar\Columnrow\:
    resource: '../Classes/*'

  Jar\Columnrow\Hooks\Datahandler\DatamapPreProcessFieldArrayHook:
    public: true
  
  Jar\Columnrow\DataProcessing\ColumnRowDataProcessor:
    public: true